#!/usr/bin/env python3

import abc
import argparse
import configparser
import urllib.parse

import icalendar

from github import Github
from redmine import Redmine
from taskw import TaskWarrior


class Issue(object):

    def __init__(self, uid, title, description, project, url, created, updated,
                 author=None, percent_done=None, start=None, due=None):
        if uid is None:
            raise ValueError('uid must not be None')
        if title is None:
            raise ValueError('title must not be None')
        if description is None:
            raise ValueError('description must not be None')
        if project is None:
            raise ValueError('project must not be None')
        if url is None:
            raise ValueError('url must not be None')
        if created is None:
            raise ValueError('created must not be None')
        if updated is None:
            raise ValueError('updated must not be None')
        self.uid = uid
        self.title = title
        self.description = description
        self.project = project
        self.url = url
        self.created = created
        self.updated = updated
        self.author = author
        self.percent_done = percent_done
        self.start = start
        self.due = due

    def __str__(self):
        return '{clazz}[uid={uid}, title={title}, ' \
           'project={project}, due={due}]'.format(
               clazz=self.__class__.__name__,
               uid=self.uid,
               title=self.title,
               project=self.project,
               due=self.due)


class IssueSource(object):
    __metaclass__ = abc.ABCMeta

    @classmethod
    @abc.abstractmethod
    def create(cls, name, config):
        """
        Factory method to create an appropriate instance of the source for the
        provided options.
        Args:
            name (str):
                user-defined name for the source
            config (configparser.SectionProxy):
                config parser section with the configuration for this source
        Raises:
            ValueError:
                Configuration for this source is inappropriate
        """
        pass

    @abc.abstractmethod
    def issues(self):
        pass


class RedmineIssueSource(IssueSource):

    def __init__(self, redmine):
        self.redmine = redmine
        self.parsed_url = urllib.parse.urlparse(redmine.url)

    def _make_id(self, issue_id):
        return '{}-{}@{}'.format(
            issue_id, self.parsed_url.path, self.parsed_url.netloc)

    @abc.abstractmethod
    def _provide_issues(self):
        pass

    def issues(self):

        source_issues = []
        for issue in self._provide_issues():
            uid = self._make_id(issue.id)
            author = self.redmine.user.get(issue.author.id)
            source_issues.append(Issue(
                uid,
                issue.subject,
                issue.description,
                issue.project.name,
                issue.url,
                issue.created_on,
                issue.updated_on,
                author=(issue.author.name, author.url),
                percent_done=issue.done_ratio,
                start=issue.start_date if hasattr(issue, 'start_date') else None,
                due=issue.due_date if hasattr(issue, 'due_date') else None))
        return source_issues


class RedmineAssignedIssueSource(RedmineIssueSource):

    @classmethod
    def create(cls, name, config):
        kwargs = {}
        if not config.getboolean('verify_ssl', fallback=True):
            kwargs['requests'] = {'verify': False}
        return cls(Redmine(config['host'], key=config['key'], **kwargs))

    def _provide_issues(self):
        return self.redmine.issue.filter(assigned_to_id='me',
                                         status_id='open')

class GithubIssueSource(IssueSource):

    @classmethod
    def create(cls, name, config):
        return cls(Github(config['token']))

    def __init__(self, github):
        self.github = github

    def _make_id(self, issue_id):
        return '{}@{}'.format(
            issue_id, 'github.com')

    def issues(self):
        issues = self.github.get_user().get_issues()

        source_issues = []
        for issue in issues:
            due = None
            if issue.milestone:
                due = issue.milestone.due_on
            source_issues.append(Issue(
                self._make_id(issue.id),
                issue.title,
                issue.body,
                issue.repository.name,
                issue.html_url,
                issue.created_at,
                issue.updated_at,
                author=(issue.user.login, issue.user.html_url),
                due=due))

        return source_issues


class IssueSink(object):
    __metaclass__ = abc.ABCMeta

    @classmethod
    @abc.abstractmethod
    def create(cls, config):
        pass

    @abc.abstractmethod
    def generate(self, issues):
        pass


class ICalIssueSink(IssueSink):

    @classmethod
    @abc.abstractmethod
    def create(cls, config):
        return cls()

    def generate(self, issues):

        calendar = icalendar.Calendar()
        calendar.add('prodid', '-//languitar//issuemapper//')
        calendar.add('version', '2.0')

        for issue in issues:
            todo = icalendar.Todo()
            todo.add('UID', issue.uid)
            todo.add('CREATED', issue.created)
            todo.add('DTSTAMP', issue.updated)
            todo.add('LAST-MODIFIED', issue.updated)
            todo.add('SUMMARY', issue.title)
            todo.add('DESCRIPTION', issue.description)
            todo.add('CATEGORIES', issue.project)
            todo.add('URL', issue.url)
            if issue.author:
                organizer = icalendar.vCalAddress(issue.author[1])
                organizer.params['CN'] = icalendar.vText(issue.author[0])
                todo.add('ORGANIZER', organizer)
            if issue.percent_done:
                todo.add('PERCENT-COMPLETE', issue.percent_done)
            if issue.start:
                todo.add('START', issue.start)
            if issue.due:
                todo.add('DUE', issue.due)
            todo.add('CLASS', 'PUBLIC')
            calendar.add_component(todo)

        return calendar.to_ical().decode('utf-8')


class CsvIssueSink(IssueSink):

    @classmethod
    @abc.abstractmethod
    def create(cls, config):
        return cls()

    def generate(self, issues):
        lines = []
        lines.append('uid,project,summary,due,author,url')
        for issue in issues:
            lines.append(
                '"{uid}","{project}","{summary}",'
                '"{due}","{author}","{url}"'.format(
                    uid=issue.uid,
                    project=issue.project,
                    summary=issue.title,
                    due=issue.due.isoformat() if issue.due else '',
                    author=issue.author[0] if issue.author else '',
                    url=issue.url))
        return '\n'.join(lines)


class TaskWarriorIssueSink(IssueSink):

    @classmethod
    @abc.abstractmethod
    def create(cls, config):
        kwargs = {}
        if 'taskrc' in config:
            kwargs['config_filename'] = config['taskrc']
        return cls(TaskWarrior(**kwargs))

    def __init__(self, task):
        self.task = task

    def generate(self, issues):

        for issue in issues:
            kwargs = {}
            if issue.due:
                kwargs['due'] = issue.due.isoformat()
            self.task.task_add(issue.title,
                               project=issue.project,
                               entry=issue.created.isoformat(),
                               **kwargs)


def main():

    argument_parser = argparse.ArgumentParser(
        description='Collects issue tracking information from multiple '
                    'sources and exports these issues into other formats',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    argument_parser.add_argument(
        'config',
        type=argparse.FileType('r'),
        help='INI-style config file describing sinks and sources.')

    args = argument_parser.parse_args()

    config = configparser.ConfigParser()
    config.read_file(args.config)

    sources = []
    source_section = [s for s in config.sections() if s.startswith('source:')]
    for section in source_section:
        name = section[len('source:'):]
        class_name = config[section]['class']
        klass = globals()[class_name]
        source = klass.create(name, config[section])
        sources.append(source)

    class_name = config['sink']['class']
    klass = globals()[class_name]
    sink = klass.create(config['sink'])

    issues = []
    for source in sources:
        issues.extend(source.issues())

    print(sink.generate(issues))


if __name__ == '__main__':
    main()
